name: Deploy to VPS

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Create deployment directory
        run: |
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" > ~/.ssh/config
          ssh vazzuniverse@103.127.98.128 'mkdir -p ~/deployment'
      
      - name: Copy codebase to VPS
        run: |
          rsync -avz --exclude 'node_modules' --exclude '.git' ./ vazzuniverse@103.127.98.128:~/deployment/
          
      - name: Write .env.local to VPS
        run: |
          echo "${{ secrets.ENV_LOCAL_CONTENT }}" > .env.local
          scp .env.local vazzuniverse@103.127.98.128:~/deployment/.env.local
      
      - name: Debug files on VPS
        run: |
          ssh vazzuniverse@103.127.98.128 '
            echo "Isi direktori ~/deployment/:"
            ls -la ~/deployment/
            echo "Isi file ~/deployment/.env.local:"
            cat ~/deployment/.env.local
          '
      
      - name: Build and deploy on VPS
        run: |
          ssh vazzuniverse@103.127.98.128 '
            cd ~/deployment || exit 1
            docker build -t backendgame:latest -f Dockerfile.prod . || exit 1
            cp docker-compose.yml ~/ || exit 1
            cd ~/ && docker compose up -d || exit 1
          '