name: Deploy to VPS

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Create deployment directory
        run: |
          # Disable host key checking for first connection
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" > ~/.ssh/config
          
          # Create a deployment directory with timestamp
          ssh vazzuniverse@103.127.98.128 'mkdir -p ~/deployment'
      
      - name: Copy codebase to VPS
        run: |
          # Sync the codebase to VPS
          rsync -avz --exclude 'node_modules' --exclude '.git' ./ vazzuniverse@103.127.98.128:~/deployment/
          
      - name: Build and deploy on VPS
        run: |
          # Copy environment file
          scp .env.local vazzuniverse@103.127.98.128:~/deployment/.env.local
          
          # Execute deployment commands on the VPS
          ssh vazzuniverse@103.127.98.128 '
            cd ~/deployment
            # Build the Docker image
            docker build -t backendgame:latest -f Dockerfile.prod .
            
            # Copy docker-compose to the home directory
            cp docker-compose.yml ~/
            
            # Run docker-compose
            cd ~/ && docker-compose up -d
          '